### ISSUE TITLE
Question regarding duplications on terminal branches

### ISSUE THREAD

**Issue by ens-sb** [DessimozLab/FastOMA#19]
Hello!

I have a question regarding duplications which happen on terminal species tree branches. How are these handled? For example, in the (Mouse,(Human,Chimp)) example from the FastOMA preprint what happens if there is a duplication on one of the terminal branches, leading to a gene tree topology like (((C1, C2),H1),(C3, H2)).

Best,
Botond

**Comment by sinamajidian** [comment]
Dear Botond

Thanks for reaching out.  For the case you mentioned, we would report C1 and C2 as within-species paralogous.  On the gene tree, we would label the internal node as below. 
<img width="905" alt="gene_Tree" src="https://github.com/DessimozLab/FastOMA/assets/41860044/4be18324-92de-4d9b-b7e9-2669c3ea6992">


So, at this taxonomic level, starting from the root, each speciation results in a group:  {H1,C1,C2}  and {C3,H2}.

We usually use [orthoxml format](https://orthoxml.org/xml/Main.html) for reporting orthology information as a nested structure of HOGs. For this case we would report like this:

```
<orthologGroup id="HOG1">
 <geneRef id="H1" />
 </paralogGroup>
   <geneRef id="C1" />
   <geneRef id="C2" />
 </paralogGroup>
</orthologGroup >
```
This defines orthologous pairs as (H1,C1) and (H2,C2). 

I hope this answers the question. We would be happy to provide more information and details if you could tell us in which context is needed. 

Best,
Sina

**Comment by ens-sb** [comment]
Thanks Sina! That answers my question.
