### ISSUE TITLE
Report step uses very large amount of memory

### ISSUE THREAD

**Issue by ens-sb** [DessimozLab/FastOMA#23]
Hello,

I have run FastOMA on about 2200 genomes. The inference of HOGs finished all right (with some tweaks in the resource config), however the `fastoma_report` step failed as it consumes a very large amount of memory (did not fit in 1200GBs!). I just wanted to let you know about this issue in the case it is possible to improve the memory usage.

Regards,
Botond

**Comment by sinamajidian** [comment]
Dear Botond

Thanks for reporting this. I was able to reproduce the error, which rooted in seaborn's `sns.displot` used for visualisation of protein length distribution in `fastoma_notebook_stat.ipynb`. Sorry for the inconveniences. We are fixing this and will update the notebook soon. 

Best,
Sina

**Comment by sinamajidian** [comment]
We decided not to include this visualization for big datasets and limit it to 100 species simply using a condition `if len(species_list)<100:` in the jupyter report file. Thanks again.
