### ISSUE TITLE
Omamer crash with latest docker image

### ISSUE THREAD

**Issue by ens-sb** [DessimozLab/FastOMA#27]
Hello FastOMA team!

We were running FastOMA on a dataset which was processed sucessfully by a previous version. However, with the latest commit and docker image we get an error in the omamer run step:
```
Traceback (most recent call last):
  File "/app/bin/omamer", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/app/lib/python3.11/site-packages/omamer/main.py", line 33, in main
    from tables import PerformanceWarning
  File "/app/lib/python3.11/site-packages/tables/__init__.py", line 44, in <module>
    from .utilsextension import get_hdf5_version as _get_hdf5_version
  File "tables/utilsextension.pyx", line 1, in init tables.utilsextension
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```
It might be related to this issue: https://stackoverflow.com/a/78641304

Best,
Botond

**Comment by sinamajidian** [comment]
Hi Botond 
Thanks for sharing your experience with the newest version. I faced that because of numpy version and documented it in the [wiki](https://github.com/DessimozLab/FastOMA/wiki/Installation-running-errors). Using the suitable version it should be fine. We are working on the FastOMA docker to make it smooth. 
Best,
Sina

**Comment by ens-sb** [comment]
Thanks for the pointers, Sina! I will try running withouth the container.
Best,
Botond

**Comment by alpae** [comment]
Hi @ens-sb

I think the from version 0.3.1 onwards, this problem should not exist anymore in the docker container. could you maybe check which version you where using exactly. if you used `latest`,  you might need to pull it again. 

Cheers Adrian

**Comment by ens-sb** [comment]
Hi Adrian,
Thanks for the fix!
Botond
