### ISSUE TITLE
.command.sh: line 2: fastoma-check-input: command not found

### ISSUE THREAD

**Issue by evolbeginner** [DessimozLab/FastOMA#29]
Dear,

Many thanks for the updated version of the amazing OMA. 

I encountered a problem when running the following in the folder `testdata/`. Would you pls mind helping me with it?

```bash
nextflow run ../FastOMA.nf           --input_folder in_folder           --omamer_db in_folder/omamerdb.h5          --output_folder out_folder          --report          -profile standard
```

![fastOMA_error](https://github.com/user-attachments/assets/0a8f1c8b-7fdf-4cac-9d0e-33b6075df36c)

The .nextflow.log file is available at [the link; expires in 30 days](https://easyupload.io/0636k9).

Any help is highly appreciated! Thanks!

best,
Sishuo

**Comment by sinamajidian** [comment]
Hi Sishuo

Thanks for using FastOMA. 
The main error is this "fastoma-check-input:command not found". This means that fastOMA is not installed correctly. 
Could you tell us how you installed it?  I would suggest using [this instruction](https://github.com/DessimozLab/FastOMA#4-manual-installation-in-condamamba-environment).

Best regards,
Sina

**Comment by sinamajidian** [comment]
Alternatively, if you want to use fastoma without installation you can run this

```
nextflow run desimozlab/FastOMA -r v0.3.1 -profile conda  --input_folder testdata/in_folder
```

**Comment by evolbeginner** [comment]
> Alternatively, if you want to use fastoma without installation you can run this
> 
> ```
> nextflow run desimozlab/FastOMA -r v0.3.1 -profile conda  --input_folder testdata/in_folder
> ```

Thanks so much! I got the following actually. I removed "-r v0.3.1" but still didn't work. Perhaps I was doing sth wrong? Thanks!

![image](https://github.com/user-attachments/assets/633976bd-4231-430a-81fd-7428423ee1d8)

**Comment by evolbeginner** [comment]
> Hi Sishuo
> 
> Thanks for using FastOMA. The main error is this "fastoma-check-input:command not found". This means that fastOMA is not installed correctly. Could you tell us how you installed it? I would suggest using [this instruction](https://github.com/DessimozLab/FastOMA#4-manual-installation-in-condamamba-environment).
> 
> Best regards, Sina

Thanks somuch Sina! I think I installed it successfully by `pip` but just got the following msg by 
```bash
nextflow run FastOMA.nf --input_folder testdata/in_folder --omamer_db testdata/in_folder/omamerdb.h5 --output_folder testdata/out_folder/ --report -profile standard
```

![image](https://github.com/user-attachments/assets/83cd32b8-1581-414f-a788-a9b5a2457c1c)

I attach the file `nextflow.log` here [.nextflow.log](https://github.com/user-attachments/files/16329892/default.nextflow.log). The resulting outdir is also attached (but I think the important file `OrthologousGroups.tsv` is successfully generated, isn't it?) 
[output.tar.gz](https://github.com/user-attachments/files/16329953/output.tar.gz).

As to the installation w/ conda or mamba, i guess there is a typo in the readme: should be a dash in `conda-environment.yml`. Also, I changed L483 in the file `FastOMA.nf`: `notebook = Channel.fromPath("$workflow.projectDir/fastoma_notebook_stat.ipynb"`  otherwise it reported "no such folder" but I might be mistaken.

Would you pls mind having a look at it? Thanks so much!!

best,
sishuo

**Comment by alpae** [comment]
Hi @evolbeginner 

I think the initial problem with running the pipeline was that nextflow's create conda environment times out quite quickly. if you then retry to run the workflow, the conda environment seems there, but is not complete.

I've increased the timeout period significantly, and it seems to work now for me. 

Adrian

**Comment by evolbeginner** [comment]
> Hi @evolbeginner
> 
> I think the initial problem with running the pipeline was that nextflow's create conda environment times out quite quickly. if you then retry to run the workflow, the conda environment seems there, but is not complete.
> 
> I've increased the timeout period significantly, and it seems to work now for me.
> 
> Adrian

Thank you so much Adrian!

**Comment by evolbeginner** [comment]
> Sina

Thank you so much Sina!
