### ISSUE TITLE
Specify max memory limit

### ISSUE THREAD

**Issue by POMulhair** [DessimozLab/FastOMA#40]
Hello,

I am hoping to run fastOMA on a dataset of 384 proteomes on a server with 72 cpus and 756Gb RAM.

When I tried to run it initially (using the line below) it maxed out the server (which was using ~200Gb on other jobs) when running the omamer search step:
`nextflow run FastOMA/FastOMA.nf --input_folder input_folder --output_folder fastoma_output --report -profile standard`

I know there's memory limits set in the config file but I'm not familiar with nextflow so am not certain on how to edit this.
**Question:** Is there a way either in the command or by editing the config or nf file that I could set a limit on RAM usage?

Apologies if this is a trivial question, I thought it may also be useful for other.
Thanks for any help you can provide.

Peter

**Comment by alpae** [comment]
Hi @POMulhair 

the nextflow pipeline will allocate memory based on the expected resource requirement. if it runs out of memory, it will retry with more memory automatically. 
To avoid requesting too much memory (more than what the cluster could provide), you can either modify the `max_memory` value in `nextflow.config` or simply pass a value on the command line when you run the pipeline:

```
nextflow run FastOMA.nf --max_memory 300.GB --input_folder ...
```

Kind regards
Adrian
