### ISSUE TITLE
How to obtain a folder similar to OrthologousGroupsFasta?

### ISSUE THREAD

**Issue by drelo** [DessimozLab/FastOMA#7]
Hi again, I run the test and everything worked fine and really fast. In the folder `rhogs_all` I got 11 HOGs with the test data. 

I have used OMA standalone and I know the usual definitions so I understand that _at least at the moment_ I need the OMA groups instead of HOGs. Working with OMA standalone, I never took advantage of the xml output, in the past I simply used the **OrthologousGroupsFasta** folder and the  **OrthologousGroups.txt** outputs. 

Is there any way to obtain all the OMA groups like those stored in the OrthologousGroupsFasta folder?  I took a look at this page https://oma-stage.vital-it.ch/oma/tools/ but I haven't used `pyham` for example, so I didn't know how to begin. Could you point me to some tutorial on how to regenerate a folder analogous to the "OrthologousGroupsFasta". Thanks!

**Comment by sinamajidian** [comment]
Dear @drelo 
Thanks for you message. 

Yes, we are working on this [feature](https://github.com/DessimozLab/FastOMA/blob/master/utils/orthoxml2OG.py) and it will be fully ready in a week or so. 

Best regards,
Sina

**Comment by drelo** [comment]
Hi Sina, thanks for the response, that would be an awesome feature. 

Best  regards

Andrés
